# 科学计算
## 浙江理工大学 沈炜

## 使用numpy包求逆矩阵
### 使用numpy包求逆矩阵非常简单
### 假定m是一个numpy和矩阵对象
### 直接调用m.I，就是求m的逆矩阵

In [1]:
m=([[1, 2], [3, 4]]) 

In [2]:
import numpy as np
matrix=np.matrix(m)
matrix

matrix([[1, 2],
        [3, 4]])

In [3]:
matrix.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [4]:
# 再一个例子
A = np.mat("1 2 3; 2 3 4; 5 4 6") #从一个字符串创建矩阵
A.I

matrix([[-0.66666667,  0.        ,  0.33333333],
        [-2.66666667,  3.        , -0.66666667],
        [ 2.33333333, -2.        ,  0.33333333]])

## 使用sympy求解线性方程组

In [5]:
from sympy import *
x = Symbol('x')
y = Symbol('y')
print(solve([2 * x - y - 3, 3 * x + y - 7],[x, y]))

{x: 2, y: 1}


## 使用scipy求解线性方程组

$\left\{
    \begin{array}{l}
            2x-y-3=0 \\
            3x+y-7=0
        \end{array}
\right.$
要改写成
$\left\{
    \begin{array}{l}
            2x-y＝3 \\
            3x+y＝7
        \end{array}
\right.$

In [6]:
import numpy as np
from scipy.linalg import solve
a = np.array([[2,-1],[3,1]])
b = np.array([3,7])
x = solve(a, b)
print(x)

[2. 1.]


$\left\{
    \begin{array}{l}
            3x_1+x_2-2x_3=5 \\
            x_1-x_2+4x_3=-2 \\
            2x_1+3x_3=2.5
        \end{array}
\right.$

In [7]:
import numpy as np
from scipy.linalg import solve
a = np.array([[3, 1, -2], [1, -1, 4], [2, 0, 3]])
b = np.array([5, -2, 2.5])
x = solve(a, b)
print(x)

[0.5 4.5 0.5]


## 自己写的消元法求解线性方程组

求解这个线性方程组
$\left\{
    \begin{array}{l}
        x + 2y +3z = 6 \\
        3x + y = 3 \\
        -x + y = 3
\end{array}
\right.$<br>
思路：先消元，再求解

In [9]:
# 一个n*n非奇异线性方程组求解函数
# Elimination：消元
def elimination_sub(A):
    for i in range(1, A.shape[0]):
        A[i] = A[i] - A[0]*(A[i,0]/A[0,0])      
    return(A)

def elimination(A):
    j = A.shape[0] - 1
    i = 0
    while j > 0:
        A[i:,i:] = elimination_sub(A[i:,i:])
        i = i + 1
        j = j - 1
    return(A)

In [10]:
import numpy as np
A = np.matrix([[1,2,3,6],[3,1,0,3],[-1,1,0,3]])
elimination(A)

matrix([[  1,   2,   3,   6],
        [  0,  -5,  -9, -15],
        [  0,   0,  -2,   0]])

In [11]:
# 求解方程组
def solveX(A = None):
    A = elimination(A)
    X = {}
    m = A.shape[0]
    for i in range(m):
        j = m-1-i
        Y = A[j,-1]
        k = i
        count = 0
        while(k>0): 
            Y = Y - A[2-k-count,-2-count]*X[2-count]
            count = count + 1
            k = k-1
        X[j] = Y/A[j,-2-i]
    return X

In [12]:
import numpy as np
A = np.matrix([[1,2,3,6],[3,1,0,3],[-1,1,0,3]])
solveX(A)

{2: -0.0, 1: 3.0, 0: 0.0}

## 使用sympy求解非线性方程组
### 方程表示
<center>公式与代码之间转换</center>

|运算|运算符
|:-|:-
|加号| +
|减号| -
|除号| /
|乘号|*
|指数|**
|对数|log()
|e的指数次幂| exp()

求解$x^2+2x-1=0$

In [8]:
from sympy import *
x= symbols('x')
print(solve(x**2+2*x+1,x))

[-1]


$\left\{
    \begin{array}{l}
            3x+x^2-2x^3=5 \\
            x-x^2+4x^3=-2 \\
            2x+3x^3=2.5
        \end{array}
\right.$

In [9]:
from sympy import *
x = Symbol('x')
print(solve([3*x+x**2-2*x**3-5, x-x**2+4*x**3+2, 2*x+3*x**3-2.5],[x]))

[]


In [10]:
#求解一个8元1次方程组
from sympy import *

a1,b1,c1,d1,a2,b2,c2,d2=symbols('a1,b1,c1,d1,a2,b2,c2,d2')
x0,x1,x2,y0,y1,y2=symbols('x0,x1,x2,y0,y1,y2')
result=solve([a1+b1*x0+c1*x0*x0+d1*x0*x0*x0-y0,
	a1+b1*x1+c1*x1*x1+d1*x1*x1*x1-y1,
	a2+b2*x1+c2*x1*x1+d2*x1*x1*x1-y1,
	a2+b2*x2+c2*x2*x2+d2*x2*x2*x2-y2,
	b1+2*c1*x1+3*d1*x1*x1-b2-2*c2*x1-3*d2*x1*x1,
	c1+3*d1*x1-c2-3*d2*x1,
	c1+3*d1*x0,
	c2+3*d2*x2],[a1,b1,c1,d1,a2,b2,c2,d2])
#设置参数
cs=[(x0,6),(x1,9),(x2,12),(y0,0),(y1,3),(y2,0)]

# print(result[a1])
# print(result[b1])
# print(result[c1])
# print(result[d1])
# print(result[a2])
# print(result[b2])
# print(result[c2])
# print(result[d2])

a1=result[a1].subs(cs)
b1=result[b1].subs(cs)
c1=result[c1].subs(cs)
d1=result[d1].subs(cs)
a2=result[a2].subs(cs)
b2=result[b2].subs(cs)
c2=result[c2].subs(cs)
d2=result[d2].subs(cs)
print(a1)
print(b1)
print(c1)
print(d1)
print(a2)
print(b2)
print(c2)
print(d2)

3
-9/2
1
-1/18
-78
45/2
-2
1/18
