# TensorFlow入门（TensorFlow Basis）
## 浙江理工大学 沈炜

## TensorFlow简介
TensorFlow™ 是一个开放源代码软件库，用于进行高性能数值计算。借助其灵活的架构，用户可以轻松地将计算工作部署到多种平台（CPU、GPU、TPU）和设备（桌面设备、服务器集群、移动设备、边缘设备等）。TensorFlow™ 最初是由 Google Brain 团队（隶属于 Google 的 AI 部门）中的研究人员和工程师开发的，可为机器学习和深度学习提供强力支持，并且其灵活的数值计算核心广泛应用于许多其他科学领域

<img src="TensorflowLogo.png">

TensorFlow™是使用数据流图进行高效数值计算的一个开源库。

## TensorFlow安装
### Anaconda下安装
- Anaconda下安装，最好先修改一下源（增加清华源），因为国外的源访问比较慢
- 打开conda命令行，执行命令： conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
- 再执行命令： conda config --set show_channel_urls yes
- 然后打开.condarc文件（用notepad），一般就在users\xxxx\下，xxxx就是用户名
<img src='1.png'>
<img src='condac.png'>

### 安装TensorFlow的CPU版本
- conda install tensorflow

### pip安装CPU版本
- pip install temsorflow==1.13.1
- pip install -i https://pypi.tuna.tsinghua.edu.cn/simple  temsorflow==1.13.1

### GPU版本安装
- Windows下安装，参考：http://note.youdao.com/noteshareid=08c23debe7e68208f6eb3a4282b09c5f&sub=2197D09412E84BAB93DD65B5A915B349
- ubuntu 16.04下安装，参考：https://github.com/williamFalcon/tensorflow-gpu-install-ubuntu-16.04
- <font color=red>虚拟方式安装，以VMware为例，只有vSphere支持PCIe passthrough，而VMware Workstation不支持</font>。

In [1]:
# 测试安装是否成功
import tensorflow as tf
tf.__version__

c:\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is depr

'1.14.0'

### 用TensorFlow说Hello World!
注意由于现在最新用的是2.4版本，和1.0有差别。

In [2]:
#import tensorflow.compat.v1 as tf  # 用1.0
#tf.disable_v2_behavior() # 关闭2.0特性
# 创建一个常值运算，作为一个节点加入到默认计算图中

import tensorflow as tf
hello = tf.constant("Hello, World!")

# 创建一个TF会话
sess = tf.Session()    # 2.0不直接支持Session()

# 运行并获得结果
print(sess.run(hello))
sess.close() # 关闭会话

b'Hello, World!'


### 数据流图（计算图）

TensorFlow程序的执行分为<font color=red>创建流图</font>、<font color=red>执行会话</font>两个部分。

TensorFlow内部将上述计算过程表征为**数据流图**，也称为**计算图**。

创建数据流图（或计算图）就是建立计算模型，执行会话则是提供数据并获得结果。

计算图是一个有向图，由以下内容构成：
- 一组节点，每个节点都代表一种运算
- 一组有向边，每个边代表实施运算所需要的数据和流转方向

TensorFlow有两种边：

- 常规边：带有节点之间的数据结构。一个节点的运算输出成为另一个节点的输入，连接两个节点的边携带着值。
- 特殊边：不携带值，仅表示两个节点之间的控制相关性。比如，$X$和$Y$之间的边可以表示只有当$X$中的运算执行完毕后才执行$Y$。
<img src='1.jpg'>
<img src="TensorFlow数据流图.gif">

In [3]:
# 一个简单计算图
node1 = tf.constant(3.0,tf.float32,name="node1")
node2 = tf.constant(4.0,tf.float32,name="node2")
node3 = tf.add(node1, node2)

In [4]:
print(node1)
print(node3)  # 注意输入的shape

Tensor("node1:0", shape=(), dtype=float32)
Tensor("Add:0", shape=(), dtype=float32)


输出的结果不是一个具体的数字，而是一个**张量的结构**

In [5]:
print(node1)
print(node2)

Tensor("node1:0", shape=(), dtype=float32)
Tensor("node2:0", shape=(), dtype=float32)


In [6]:
# 建立会话并显示运行结果
sess = tf.Session()
print("运行sess.run(node2)的结果：", sess.run(node2))

运行sess.run(node2)的结果： 4.0


In [7]:
# 更新变量并返回计算结果
print("运行sess.run(node3)的结果：", sess.run(node3))

# 关闭session
sess.close()

运行sess.run(node3)的结果： 7.0


### 张量作为类型的属性

Tensor("add:0", shape=(2,), dtype=float32)

名字（name）

	“node:src_output”：node 节点名称，src_output 来自节点的第几个输出
    
形状（shape）

	张量的维度信息， shape=(2,) 一维数组，长度为2
    
类型（type）：data type of tensor's elements

	每一个张量会有一个唯一的类型。
    
	TensorFlow会对参与运算的所有张量进行类型的检查，发现类型不匹配时会报错   

### 张量作为概念的属性
- <font color=red>**阶**</font>（Rank）、秩，**rank：number of dimensions**
- <font color=red>**形状**</font>，**shape: number of rows and columns**

<img src="张量的阶.png">
shape=(3,)
shape=(3,3)
shape=(3,3,1)

#### 获取张量的元素

阶为1的张量等价于向量（列表）,通过t[i]获取元素；

阶为2的张量等价于矩阵，通过t[i,j] 获取元素；

阶为3的张量，通过t[i,j,k] 获取元素；

In [8]:
import tensorflow as tf
tens1 = tf.constant([[[1,2],[2,3]],[[3,4],[5,6]]])
print(tens1)
sess = tf.Session()
print(sess.run(tens1))
print(sess.run(tens1)[1,1,0])
sess.close()

Tensor("Const_1:0", shape=(2, 2, 2), dtype=int32)
[[[1 2]
  [2 3]]

 [[3 4]
  [5 6]]]
5


### 张量的形状（Shape）

In [9]:
import tensorflow as tf
tens1 = tf.constant([[[1,2],[2,3]],[[3,4],[5,6]],[[7,8],[9,10]]])

print(tens1)

Tensor("Const_2:0", shape=(3, 2, 2), dtype=int32)


In [10]:
import tensorflow as tf

scalar = tf.constant(100)
vector = tf.constant([1, 2, 3, 4, 5])
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
cube_matrix = tf.constant([[[1], [2], [3]], [[4], [5], [6]], [[7], [8], [9]]])

print(scalar.get_shape())
print(vector.get_shape())
print(matrix.get_shape())
print(cube_matrix.get_shape())

()
(5,)
(2, 3)
(3, 3, 1)


### 张量的数据类型
<img src='type.jpg'>

默认类型：

不带小数点的数会被默认为**int32**

带小数点的会被默认为**float32**


In [13]:
import tensorflow as tf
a = tf.constant([1, 2], name="a")
b = tf.constant([2.0, 3.0], name="b") # 注意类型
print(a,b)
result = a + b

Tensor("a_2:0", shape=(2,), dtype=float32) Tensor("b_2:0", shape=(2,), dtype=float32)


运行报错：

ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("b_3:0", shape=(2,), dtype=float32)'

TensorFlow会对参与运算的所有张量进行类型的检查，发现类型不匹配时会报错


### 会话 Session
- 管理神经网络运行的一个对象
- 会话拥有并管理TensorFlow程序运行时的所有资源
- 当所有计算完成之后需要关闭会话帮助系统回收资源

### 会话的典型模式1

In [11]:
# 创建一个会话
sess = tf.Session()
#使用这个创建好的会话来得到关心的运算的结果。比如可以调用 sess.run(result)
#来得到张量result的取值
print(sess.run(result)) # 这个result要加，否则会有错误
#关闭会话使得本次运行中使用到的资源可以被释放
sess.close()

NameError: name 'result' is not defined

**需要明确调用 Session.close函数来关闭会话并释放资源**

### 会话的典型模式2 


In [12]:
node1 = tf.constant(3.0,tf.float32,name="node1")
node2 = tf.constant(4.0,tf.float32,name="node2")
# result = node1 + node2
result = tf.add(node1, node2)

#创建一个会话，并通过Python中的上下文管理器来管理这个会话
with tf.Session() as sess:  # sess=tf.Session()
    #使用这创建好的会话来计算结果
    print(sess.run(result))
# 不需要再调用 Session.close() 函数来关闭会话
# 当上下文退出时会话关闭和资源释放也自动完成了


7.0


### 指定默认的会话

TensorFlow不会自动生成默认的会话，需要手动指定

当默认的会话被指定之后可以通过 tf.Tensor.eval 函数来计算一个张量的取值

In [13]:
node1 = tf.constant(3.0,tf.float32,name="node1")
node2 = tf.constant(4.0,tf.float32,name="node2")
result = tf.add(node1, node2)

sess = tf.Session()
with sess.as_default():  # 没有显式地调用sess.run()
    print(result.eval())

7.0


下面代码也可以完成相同的功能

In [14]:
sess = tf.Session()

#下面两个命令有相同的功能
print(sess.run(result))

print(result.eval(session=sess))


7.0
7.0


### 交互式环境下设置默认会话

在交互式环境下，Python脚本或者Jupyter编辑器下，通过设置默认会话来获取张量的取值更加方便

tf.InteractiveSession 使用这个函数会<font color=red>自动将生成的会话注册为默认会话</font>


In [15]:
node1 = tf.constant(3.0,tf.float32,name="node1")
node2 = tf.constant(4.0,tf.float32,name="node2")
result = tf.add(node1, node2)

sess = tf.InteractiveSession()
print(result.eval())
sess.close()

7.0


### 常量

In [16]:
a = tf.constant(1.0, name='a')
b = tf.constant(2.5, name='b')
c = tf.add(a, b, name='c')

sess = tf.Session()
c_value = sess.run(c)
print(c_value)
sess.close()

3.5


### 变量

由TensorFlow系统内部进行调整的动态参数

创建语句：

name_variable = tf.Variable(value, name)

注意V是大写字母

初始化语句：

个别变量初始化：

init_op = name_variable.initializer()

所有变量初始化：

init_op = tf.global_variables_initializer()


In [18]:
node1 = tf.Variable(3.0,tf.float32,name="node1")
node2 = tf.Variable(4.0,tf.float32,name="node2")
result = tf.add(node1, node2, name='add')

sess = tf.Session()

#变量初始化,变量必须要初始化
init = tf.global_variables_initializer()
sess.run(init)
#sess.run(result)

print(sess.run(result))

7.0


以上代码在Session会话变量后，增加了一个init初始化变量，并调用会话的run命令对参数进行初始化。

<font color=red>使用了Variable变量类型，不进行初始化数值会出现运行错误</font>

### 变量赋值 assign

In [19]:
import tensorflow as tf

value = tf.Variable(0, name="value")
one = tf.constant(1)
new_value = tf.add(value, one)
update_value = tf.assign(value, new_value)  # 注意update_value应理解为赋值这个过程

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print('at first',sess.run(value))
    for _ in range(10):
        sess.run(update_value)
        print(sess.run(value))

at first 0
1
2
3
4
5
6
7
8
9
10


**与传统编程语言不同，TensorFlow中的变量一般定义后，无须人工手动赋值，系统会根据算法模型自动调整变量的数值。后面在将机器学习模型训练时会更能体会，比如权重Weight变量w，经过多次迭代，会自动调整。**

### 占位符

TensorFlow中的Variable变量类型，在定义时需要初始化值，但有些变量定义时并不知道其数值，只有当真正开始运行程序时，才由外部输入，比如训练数据，这时候需要用到占位符

tf.placeholder占位符，是TensorFlow中特有的一种数据结构，类似动态变量，或者传统语言的“宏替换”符号；

TensorFlow占位符Placeholder，先定义一种数据，其参数为数据的Type和Space，占位符Placeholder的函数接口如下：

tf.placeholder(dtype, shape=None, name=None)

In [28]:
x = tf.placeholder(tf.float32, (2, 2), name='tx')
# 此代码生成一个2x2的二维矩阵，矩阵中每个元素的类型都是tf.float32，内部对应的符号名称是tx

### Feed提交数据和Fetch提取输出


In [18]:
a = tf.placeholder(tf.float32, name='ta')
b = tf.placeholder(tf.float32, name='tb')
c = tf.multiply(a, b, name='tc')

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    result = sess.run(c, feed_dict={a:15.0, b:3.5})
    print(result)

52.5


In [20]:
a = tf.placeholder(tf.float32, name='ta')
b = tf.placeholder(tf.float32, name='tb')
c = tf.multiply(a, b, name='tc')
d = tf.subtract(a, b, name='td')

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    result = sess.run([c,d], feed_dict={a:[8.0,2.0,3.5], b:[1.5,2.0,4.]})
    print(result)
    print(result[0],result[1])

[array([12.,  4., 14.], dtype=float32), array([ 6.5,  0. , -0.5], dtype=float32)]
[12.  4. 14.] [ 6.5  0.  -0.5]


### 可视化 TesnorBoard

TensorBoard是TensorFlow的可视化工具

通过TensorFlow程序运行过程中输出的日志文件可视化TensorFlow程序的运行状态

TensorBoard和TensorFlow程序跑在不同的进程中


In [21]:
import tensorflow as tf

# logdir改为自己机器上的合适路径
logdir='d:/log'

#定义一个简单的计算图，实现向量加法的操作
input1 = tf.constant([1.0, 2.0, 3.0], name="input1")
input2 = tf.Variable(tf.random_uniform((3,)), name="input2")  # 产生1维3个分量的向量
output = tf.add_n([input1, input2], name="add")

#生成一个写日志的writer，并将当前的TensorFlow计算图写入日志。
writer = tf.summary.FileWriter(logdir,tf.get_default_graph())
writer.close()


Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
tf.float32 has type DType, but expected one of: int, long, bool
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
tf.float32 has type DType, but expected one of: int, long, bool


生成的文件
<img src="log.png">

#### 启动TensorBoard

TensorBoard不需要额外安装，在TensorFlow安装时已自动完成

在Anaconda Prompt中运行TensorBoard，并将日志的地址指向程序日志输出的地址

命令：tensorboard --logdir=/path/log --host=localhost
<img src="启动TensorBoard.png">

启动服务的端口默认为6006；使用 --port 参数可以改编启动服务的端口

<font color=red>在log目录下运行</font>

#### 访问TensorBoard

浏览器访问网址

http://localhost:6006

<img src="浏览器访问TensorBoard.png">


#### TensorBoard常用API

<img src="TensorBoardAPI.png">

## 实验题
请你用TensorFlow实现10个整数（constant）的排序，并用TensorBoard显示过程。